### ISSUE TITLE
live console problem

### ISSUE THREAD

**Issue by dgomez13** [easy-wi/developer#1251]
i have some csgo servers

when I try to access the server live console it looks like this:

Can not download screenlog from server / csgo / screenlog.0

![problem console](https://user-images.githubusercontent.com/67635257/86116862-6a705f00-bace-11ea-9520-7b97a4ad9b08.PNG)

two servers with ubuntu:
1 with ubuntu 16 and the gameserver root
2 with ubuntu 18 and the easy-wi panel

Ftp works properly when i try with filezilla, port (21) its open

Someone can help me with this

**Comment by GLITCH-Jan** [comment]
Hey,
Did you changed the FTP Password in the Interface?
Did you changed the user Password via shell?
Is EasyWI installed via Script?

cheers,
Jan

**Comment by dgomez13** [comment]
no password has changed

easy-wi panell installed via web, cloning the files in github project

**Comment by GLITCH-Jan** [comment]
Can you use the FTP user with Filezilla?

If not what is the error message and what says the log

**Comment by dgomez13** [comment]
yes with filezilla ftp works fine.

**Comment by GLITCH-Jan** [comment]
Ok... 

Try again with the panel and check the LOG files ...
Check if the needed Packages are installed (php etc)...

maybe the panel is denied by the server or the panel cant even establish a connection

**Comment by dgomez13** [comment]
I try with de log in the panel but have 0 information about this, what log i need to check??

the packages needed only in the easy-wi panel server rigth?

**Comment by dgomez13** [comment]
Still the same with the panel and the console, i cant find the correct log file

**Comment by cyberlimbo** [comment]
Same problem here ;)

**Comment by primeas-de** [comment]
/etc/proftpd/proftpd.conf
Line: 73
Umask 022 022

Could be a chmod error if easy-wi "proftpd" updated

**Comment by dgomez13** [comment]
Yes the screenlog file exist in the game server,

The webftp works correctly, I can browse the directories.

my configuration in the proftpd.conf is umask 077 077, what thats mean??

**Comment by primeas-de** [comment]
I use Debian 10 with Easy-wi only as a game server interface and Apache2 + ProFTPD via another panel (Froxlor). If I install easy-wi (stable installer) and set Update / Install Proftpd to Yes, the installer changes the unmask of proftpd. All files or folders that are then created have the wrong CHMOD and cannot be read. Unmask 022 022 sets the correct CHMOD again and it runs without problems. It may be the fault why the Easy-Wi interface cannot read the screen log file because the CHMOD is not correct.

**Comment by dgomez13** [comment]
Weel i try to change in the proftpd.conf the umask in the gameserver root to 022 and the users via ftp get 644 for files and 755 for directorys, but the problem still the same with de liveconsole, i try to change all the permissions to 777 and nothing change for the liveconsole always this error message "Cannot download screenlog from server / csgo / screenlog.0"

**Comment by Nexus633** [comment]
Is a screenlog.0 file in server/csg/? Who is the owner of this file? Is the owner of this file the same owner of the other files?

**Comment by dgomez13** [comment]
-Screenlog.0 in server/csgo 
- The owner is the user of all the files in this csgo server, the user created in the easy-wi panel with a 17 in this case all the servers have a user with the username of the user panel and a number like this username-17

**Comment by Nexus633** [comment]
I try to reconstruct the error and then see what could be the reason. Can you please tell me your system? Webhost and gamehost

**Comment by dgomez13** [comment]
Two servers
first ubuntu 18 php 7.3 easy-wi panel proftp and apache
second with ubuntu 16 game-root, proftp and csgo servers
all in AWS

**Comment by Nexus633** [comment]
Thank you! I will equip my test system with Ubuntu 16 and try to reconstruct the error. I will then get back to you. Please be patient

**Comment by Nexus633** [comment]
I can not reproduce the error. I tried Ubuntu 16.04.18.04 and 20.04. Everywhere I get the console displayed. Do you have enough disk space? I could still look directly at you, that's why you write to me in the discord of easy-wi. I would then need admin access from you, root data (the easy account is sufficient) and FTP data for easy-wi.

**Comment by cyberlimbo** [comment]
In case you find the solution, please publish it in this thread, i'm with the same problem :(

**Comment by Nexus633** [comment]
> In case you find the solution, please publish it in this thread, i'm with the same problem :(

I can not reproduce the error. My systems works fine.

I could still look directly at you, that's why you write to me in the discord of easy-wi. I would then need admin access from you, root data (the easy account is sufficient) and FTP data for easy-wi.

The i can Look on your Code and your error reason. Then i can fix them an make a pull request.

Easy-wi Discord Name: Nexus633

**Comment by GLITCH-Jan** [comment]
Hey,
@dgomez13  can you enable the Debug mode on your webpanel with /stuff/config.php  Debug = 1 ?
If you made this already please send us any error that should be displayed on the panel site.

**Comment by cyberlimbo** [comment]
//Solved by editing the proftpd port to the default one.
Port 21
*I was using a different one.

**Comment by dgomez13** [comment]
Thank you all for the help, finally after several attempts was found the solution was proftpd that was banning the ip of the other server because it was connecting with an ip, but then sent the private ip of the machine and recognized it as different from the previous, so adding the following guideline to proftpd works correctly "AllowForeignAddress on"
