### ISSUE TITLE
Starbound

### ISSUE THREAD

**Issue by DAThosting** [easy-wi/developer#960]
Template doesn't work anymore.

Starbound version: 1.2.1

There are many changes in the newer starbound version.
Tried to change it myself but the problem is, the server requires a full starbound_server.config if I only want to set the maxPlayers the whole file will be overridden to the default config.

Maybe @FV-Chris should test it too.

**Comment by ulrichblock** [comment]
Neither do I have the files, nor the game. Also there is the matter of lack of time to study the game.

Please provide a solution/template, we could pull.

**Comment by Qhiliqq** [comment]
Okay no problem.

I tested many options but didn't get this working.

The problem is:
In Cvars I wrote this:

> [storage/starbound_server.config] txt
> "gameServerBind" : "%ip%",
> "gameServerPort" : %port%,
> "maxPlayers" : %slots%,
> "queryServerBind" : "%ip%",
> "queryServerPort" : %port%,
> "rconServerBind" : "%ip%",
> "rconServerPort" : %port2%,

Tested also:

> [storage/starbound_server.config] json
> gameServerBind:%ip%
> gameServerPort:%port%
> maxPlayers:%slots%
> queryServerBind:%ip%
> queryServerPort:%port%
> rconServerBind:%ip%
> rconServerPort:%port2%

but this generate everytime a new config instead of changing the existing.

**Comment by Qhiliqq** [comment]
Why symfony override files and not changing necessary lines of the file?
If this would work then all problems solved...

**Comment by ulrichblock** [comment]
We do not use Symfony, as it is a full blown PHP Framework. So you have me confused. You define json/txt content.

What are you actually trying to achieve?

**Comment by Qhiliqq** [comment]
I first used the delivered starbound template from ew directly.
Then I started the server and got a lot of errors...

After a while I found many changes in Starbound directory tree.
So I started to fix the template.
Now the problem is, Starbound needs a complete starbound_server.config.
If I only post the port, ip etc. the server automatically rename it and create a new one.

Also I found out that the server-generated config doesn't support the ew-generated config:
http://pastebin.com/wFQns7Dt <- This is the server-generated config
http://pastebin.com/djjJna6e <- This is the ew-generated config
So I used the server-generated file and edit it with the values of ew-generated then there was another error. As you can see the port fields in the server-generated config hasn't got ticks (" ") if I delete the ticks, the server started successfully, so this is int and not a string... How I can define this?
The config should be json, this is written here http://starbound.gamepedia.com/Starbound.config.

This is my Starbound Cvars:

> [storage/starbound_server.config] json
> gameServerBind:%ip%
> gameServerPort:%port%
> maxPlayers:%slots%
> queryServerBind:%ip%
> queryServerPort:%port%
> rconServerBind:%ip%
> rconServerPort:%port2%

**Comment by DAThosting** [comment]
bump
